### PR TITLE
[TEST] update to cb3 using `conda smithy update-cb3`

### PR DESCRIPTION
**Pull request by shadowwalkersb**
Ran `conda smithy update-cb3` that's proposed in PR https://github.com/conda-forge/conda-smithy/pull/781 to update the recipe to cb3. So, are the added C compilers to this recipe needed?

```
$ conda smithy update-cb3
List of changes done to the recipe:
Renamed build with host
Removing vc features
Removing features section as it is empty
Adding C compiler
```

cc @isuruf

### CODE REVIEW

**Comment by mbargull** [comment]
> So, are the added C compilers to this recipe needed?

Yep, it builds extension modules, see: https://github.com/libgit2/pygit2/blob/v0.27.1/setup.py

**Comment by shadowwalkersb** [comment]
@conda-forge-admin, please re-render.

**Comment by isuruf** [comment]
Btw, please use forks for PRs in the future

**Comment by shadowwalkersb** [comment]
> Btw, please use forks for PRs in the future

Yeah, sorry. It gets easier to get confused when we have three remotes, conda-forge, personal fork and bot's fork.

**Comment by mbargull** [comment]
> Btw, please use forks for PRs in the future

Good catch, @isuruf, I didn't even notice before.
@shadowwalkersb, it's rather important to do so since you insta-release on any branch of the main repo; see the new builds from this branch at https://anaconda.org/conda-forge/pygit2/files.
For more information, see: https://conda-forge.org/docs/conda-forge_gotchas.html#using-a-fork-vs-a-branch-when-updating-a-recipe.

**Comment by shadowwalkersb** [comment]
Yeah, sounds like messed up big time. Let me remove myself. Probably, the safest thing to do.

**Comment by mbargull** [comment]
Nah, don't be too harsh on yourself. That *unconditionally* uploading for new branches is a [longstanding issue](https://github.com/conda-forge/conda-forge.github.io/issues/87) that quite a few people tripped over before.
And https://github.com/conda-forge/pygit2-feedstock/commits/master shows you did a good job maintaining the feedstock lately -- I'd like to encourage you to continue to do so :smile:.

**Pull request closed without merging**
